import { getCurrentUser } from "@/lib/supabase/auth";
import { getWorkspaceInviteByToken } from "@/lib/workspace-admin";
import { WorkspaceInviteAction } from "@/components/workspace-invite-action";
import Link from "next/link";
export default async function WorkspaceInvitePage({ params }: { params: Promise<{ token: string }> }) {
  const token = (await params).token; const invite = await getWorkspaceInviteByToken(token); const user = await getCurrentUser();
  const valid = invite?.status === "pending" && new Date(invite.expires_at).getTime() > Date.now();
  return <main className="mx-auto flex min-h-screen max-w-xl items-center px-5 py-12"><section className="w-full rounded-md border border-border bg-panel p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted-foreground">Skill Dockyard</p>{!invite || !valid ? <><h1 className="mt-4 text-3xl font-black">Invitation unavailable</h1><p className="mt-3 text-muted-foreground">This invitation may have expired, been used, or been revoked.</p></> : <><h1 className="mt-4 text-3xl font-black">Join {invite.workspace_name}</h1><p className="mt-3 text-muted-foreground">You’ve been invited as a {invite.role}. This invitation expires {new Date(invite.expires_at).toLocaleDateString()}.</p>{!user ? <div className="mt-6 flex gap-3"><Link className="rounded-md bg-primary px-4 py-2 text-sm font-semibold text-white" href={`/login?next=${encodeURIComponent(`/invite/${token}`)}`}>Log in</Link><Link className="rounded-md border border-border px-4 py-2 text-sm font-semibold" href={`/signup?next=${encodeURIComponent(`/invite/${token}`)}`}>Create account</Link></div> : user.email?.trim().toLowerCase() !== invite.email ? <p className="mt-6 rounded-md border border-border bg-muted p-4 text-sm">This invitation is addressed to <strong>{invite.email}</strong>. Sign in with that email to accept it.</p> : <div className="mt-6"><WorkspaceInviteAction token={token} /></div>}</>}</section></main>;
}
