"use client";

import { ProductLink as Link } from "@/components/product-link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Anchor } from "lucide-react";
import { createBrowserSupabase } from "@/lib/supabase/browser";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function AuthForm({ mode }: { mode: "login" | "signup" }) {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState<string | null>(null); const [pending, setPending] = useState(false); const signup = mode === "signup";
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(null); try { const client = createBrowserSupabase(); if (signup) { const origin = process.env.NEXT_PUBLIC_SITE_URL ?? window.location.origin; const { error } = await client.auth.signUp({ email, password, options: { emailRedirectTo: `${origin}/auth/confirm?next=/app` } }); if (error) throw error; setMessage("Check your inbox for a confirmation link. It opens your private workspace when you confirm."); } else { const { error } = await client.auth.signInWithPassword({ email, password }); if (error) throw error; router.push("/app" as never); router.refresh(); } } catch (error) { setMessage(error instanceof Error ? error.message : "We could not complete that request."); } finally { setPending(false); } }
  return <main className="mx-auto flex min-h-screen max-w-md items-center px-5 py-12"><section className="w-full rounded-md border border-border bg-panel p-6 shadow-sm"><Link href="/" className="mb-8 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-md bg-primary text-white"><Anchor className="h-5 w-5" /></span><span className="text-lg font-black">Skill Dockyard</span></Link><h1 className="text-3xl font-black">{signup ? "Create your account" : "Welcome back"}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{signup ? "Use your work email to start a private skill library. We’ll send a confirmation link before your workspace opens." : "Sign in to your private Skill Dockyard workspace."}</p><form className="mt-6 space-y-4" onSubmit={submit}><label className="grid gap-2 text-sm font-bold">Email<Input type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></label><label className="grid gap-2 text-sm font-bold">Password<Input type="password" autoComplete={signup ? "new-password" : "current-password"} minLength={8} required value={password} onChange={(event) => setPassword(event.target.value)} /></label><Button className="w-full" type="submit" disabled={pending}>{pending ? "Working..." : signup ? "Create account" : "Log in"}</Button></form>{message ? <p className="mt-4 rounded-md border border-border bg-background p-3 text-sm leading-6 text-muted-foreground">{message}</p> : null}<p className="mt-6 text-sm text-muted-foreground">{signup ? "Already have an account?" : "Need an account?"} <Link className="font-bold text-primary underline underline-offset-4" href={signup ? "/login" : "/signup"}>{signup ? "Log in" : "Sign up"}</Link></p></section></main>;
}
