import { ArrowRight, Clock3, UserRound } from "lucide-react";
import { ProductLink as Link } from "@/components/product-link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatDate } from "@/lib/utils";
import { proposalStatusLabel, proposalStatusVariant, type ProposalListItem } from "@/lib/proposals";
import { ProposalWithdrawButton } from "@/components/proposal-withdraw-button";

export function ProposalTable({ proposals, reviewQueue = false }: { proposals: ProposalListItem[]; reviewQueue?: boolean }) {
  if (!proposals.length) {
    return <div className="rounded-md border border-border bg-panel p-8 text-center"><p className="font-black">{reviewQueue ? "Nothing needs review" : "No submissions yet"}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{reviewQueue ? "New submissions from your workspace will appear here." : "Add a skill or submit an update to start building your review history."}</p>{!reviewQueue ? <div className="mt-5 flex flex-wrap justify-center gap-3"><Button asChild><Link href="/submit">Add skill<ArrowRight className="h-4 w-4" /></Link></Button><Button asChild variant="outline"><Link href="/submit/update">Submit an update<ArrowRight className="h-4 w-4" /></Link></Button></div> : null}</div>;
  }

  return <div className="overflow-hidden rounded-md border border-border bg-panel"><div className="divide-y divide-border">{proposals.map((proposal) => <article key={proposal.id} className="grid gap-4 p-5 lg:grid-cols-[1fr_auto] lg:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Link href={`/artifacts/${proposal.artifact_id}`} className="font-black hover:underline">{proposal.artifact_name}</Link><Badge variant={proposal.kind === "update" ? "outline" : "secondary"}>{proposal.kind === "update" ? "Update" : "New skill"}</Badge><Badge variant={proposalStatusVariant(proposal.status)}>{proposalStatusLabel(proposal.status)}</Badge></div><p className="mt-2 truncate text-sm text-muted-foreground">{proposal.artifact_path}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5" />Submitted {formatDate(proposal.created_at)}</span>{proposal.submitter_email ? <span className="inline-flex items-center gap-1"><UserRound className="h-3.5 w-3.5" />{proposal.submitter_email}</span> : null}</div></div><div className="flex flex-wrap gap-2 lg:justify-end"><Button asChild variant="outline" size="sm"><Link href={`/artifacts/${proposal.artifact_id}/review?proposal=${proposal.id}`}>{reviewQueue ? "Review submission" : "View submission"}<ArrowRight className="h-3.5 w-3.5" /></Link></Button>{!reviewQueue && proposal.status === "pending_review" ? <ProposalWithdrawButton proposalId={proposal.id} /> : null}{!reviewQueue && proposal.status === "changes_requested" ? <Button asChild size="sm"><Link href={`/artifacts/${proposal.artifact_id}/update`}>Submit follow-up<ArrowRight className="h-3.5 w-3.5" /></Link></Button> : null}</div></article>)}</div></div>;
}
