"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { WorkspaceInvite, WorkspaceMembership } from "@/lib/types";
export function WorkspaceAdminPanel({ workspace, members, invites, isOwner, consistent }: { workspace: { id: string; name: string }; members: WorkspaceMembership[]; invites: WorkspaceInvite[]; isOwner: boolean; consistent: boolean }) {
  const router = useRouter(); const [name, setName] = useState(workspace.name); const [email, setEmail] = useState(""); const [role, setRole] = useState("viewer"); const [message, setMessage] = useState<string | null>(null); const [inviteUrl, setInviteUrl] = useState<string | null>(null); const [pending, setPending] = useState(false);
  async function rename(event: React.FormEvent) { event.preventDefault(); setPending(true); setMessage(null); const response = await fetch("/api/workspace", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name }) }); const payload = await response.json(); setPending(false); setMessage(response.ok ? "Workspace renamed." : payload.error ?? "We could not rename the workspace."); if (response.ok) router.refresh(); }
  async function invite(event: React.FormEvent) { event.preventDefault(); setPending(true); setMessage(null); const response = await fetch("/api/workspace-invites", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, role }) }); const payload = await response.json(); setPending(false); if (!response.ok) { setMessage(payload.error ?? "We could not create the invitation."); return; } setInviteUrl(`${window.location.origin}${payload.inviteUrl}`); setEmail(""); setMessage("Invitation created. Copy the link to send it securely."); router.refresh(); }
  async function revoke(id: string) { setPending(true); await fetch(`/api/workspace-invites/${id}/revoke`, { method: "POST" }); setPending(false); router.refresh(); }
  return <div className="space-y-8"><section className="rounded-md border border-border bg-panel p-5"><h2 className="text-xl font-black">Workspace identity</h2><p className="mt-1 text-sm text-muted-foreground">The workspace name is visible to its members. Only the owner can change it.</p><form className="mt-4 flex max-w-xl gap-3" onSubmit={rename}><Input disabled={!isOwner || !consistent} maxLength={80} value={name} onChange={(event) => setName(event.target.value)} aria-label="Workspace name" /><Button disabled={!isOwner || !consistent || pending}>Rename</Button></form></section><section className="rounded-md border border-border bg-panel p-5"><h2 className="text-xl font-black">Members</h2><div className="mt-4 divide-y divide-border">{members.map((member) => <div key={member.id} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><span>{member.email ?? member.user_id ?? "Member"}</span><span className="font-bold capitalize">{member.role}</span></div>)}</div></section>{isOwner && consistent ? <section className="rounded-md border border-border bg-panel p-5"><h2 className="text-xl font-black">Invite a member</h2><p className="mt-1 text-sm text-muted-foreground">Workspace access is separate from sharing an individual skill. Links expire in 7 days.</p><form className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto_auto]" onSubmit={invite}><Input type="email" required placeholder="teammate@example.com" value={email} onChange={(event) => setEmail(event.target.value)} aria-label="Invite email" /><select className="h-10 rounded-md border border-border bg-background px-3 text-sm" value={role} onChange={(event) => setRole(event.target.value)} aria-label="Invite role"><option value="viewer">Viewer</option><option value="editor">Editor</option><option value="reviewer">Reviewer</option></select><Button disabled={pending}>Create invite link</Button></form>{inviteUrl ? <div className="mt-4 rounded-md bg-muted p-3 text-sm break-all">{inviteUrl}</div> : null}{invites.length ? <div className="mt-6 space-y-2"><h3 className="font-bold">Pending invitations</h3>{invites.map((invite) => <div key={invite.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-border py-3 text-sm"><span>{invite.email} · {invite.role}</span><Button variant="outline" size="sm" disabled={pending} onClick={() => void revoke(invite.id)}>Revoke</Button></div>)}</div> : null}</section> : null}{message ? <p className="text-sm font-semibold text-muted-foreground">{message}</p> : null}</div>;
}
